site_name: Notes
docs_dir: ./source
theme:
  name: material

plugins:
    - search
    - table-reader
    - autolinks  
    - tags:
        tags_file: tags.md

markdown_extensions:
    - toc
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - pymdownx.highlight
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets
    - pymdownx.keys
    - footnotes

extra_javascript:

  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML    
  - javascripts/config.js
